pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from GitHub...'
                git branch: 'master', url: 'https://github.com/amoghkrrish/jenkins-pipeline.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t flask-ci:v1 .'
            }
        }
        stage('Test') {
            steps {
                echo 'Running container briefly to test...'
                sh 'docker run --rm flask-ci:v1 python -c "print(\"App imported successfully\")"'
            }
        }
    }
}
