
pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                dir('day2-github-integration') {
                    echo 'Building Docker image...'
                    sh 'docker build -t flask-ci:v1 .'
                }
            }
        }
        stage('Test') {
            steps {
                dir('day2-github-integration') {
                    echo 'Running quick test...'
                    sh '''docker run --rm flask-ci:v1 python -c "print('App imported successfully')"''                }
               }
           }
        }
    }
}
