pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t flask-ci:v1 .'
            }
        }
        stage('Test') {
            steps {
                echo 'Running quick test...'
                sh 'docker run --rm flask-ci:v1 python -c "print(\"App imported successfully\")"'
            }
        }
    }
}
